// frontend/src/store/types.js

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKET = 'GET_TICKET';
export const CREATE_TICKET = 'CREATE_TICKET';
export const TICKET_ERROR = 'TICKET_ERROR';

export const GET_BUSINESS_CENTERS_SUCCESS = 'GET_BUSINESS_CENTERS_SUCCESS';
export const GET_BUSINESS_CENTERS_FAIL = 'GET_BUSINESS_CENTERS_FAIL';

export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_FAIL = 'CREATE_TICKET_FAIL';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAIL = 'GET_TICKETS_FAIL';

export const ASSIGN_ENGINEER_SUCCESS = 'ASSIGN_ENGINEER_SUCCESS';
export const ASSIGN_ENGINEER_FAIL = 'ASSIGN_ENGINEER_FAIL';

export const GET_ENGINEERS_SUCCESS = 'GET_ENGINEERS_SUCCESS';
export const GET_ENGINEERS_FAIL = 'GET_ENGINEERS_FAIL';

export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS';
export const GET_TICKET_FAIL = 'GET_TICKET_FAIL';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';


export const UPDATE_TICKET_STATUS_SUCCESS = 'UPDATE_TICKET_STATUS_SUCCESS';
export const UPDATE_TICKET_STATUS_FAIL = 'UPDATE_TICKET_STATUS_FAIL';


export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';


export const GET_USERS_BY_BC_SUCCESS = 'GET_USERS_BY_BC_SUCCESS';
export const GET_USERS_BY_BC_FAIL = 'GET_USERS_BY_BC_FAIL';

// Здесь храним типы экшенов для пользователей (и т.д.)
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const ARCHIVE_USER_REQUEST = "ARCHIVE_USER_REQUEST";
export const ARCHIVE_USER_SUCCESS = "ARCHIVE_USER_SUCCESS";
export const ARCHIVE_USER_FAIL = "ARCHIVE_USER_FAIL";

export const UNARCHIVE_USER_REQUEST = "UNARCHIVE_USER_REQUEST";
export const UNARCHIVE_USER_SUCCESS = "UNARCHIVE_USER_SUCCESS";
export const UNARCHIVE_USER_FAIL = "UNARCHIVE_USER_FAIL";

// src/store/types.js

// Получение списка
export const GET_BUSINESS_CENTERS_REQUEST = "GET_BUSINESS_CENTERS_REQUEST";

// Создание
export const CREATE_BUSINESS_CENTER_REQUEST = "CREATE_BUSINESS_CENTER_REQUEST";
export const CREATE_BUSINESS_CENTER_SUCCESS = "CREATE_BUSINESS_CENTER_SUCCESS";
export const CREATE_BUSINESS_CENTER_FAIL = "CREATE_BUSINESS_CENTER_FAIL";

// Обновление (редактирование)
export const UPDATE_BUSINESS_CENTER_REQUEST = "UPDATE_BUSINESS_CENTER_REQUEST";
export const UPDATE_BUSINESS_CENTER_SUCCESS = "UPDATE_BUSINESS_CENTER_SUCCESS";
export const UPDATE_BUSINESS_CENTER_FAIL = "UPDATE_BUSINESS_CENTER_FAIL";

// Архивирование
export const ARCHIVE_BUSINESS_CENTER_REQUEST = "ARCHIVE_BUSINESS_CENTER_REQUEST";
export const ARCHIVE_BUSINESS_CENTER_SUCCESS = "ARCHIVE_BUSINESS_CENTER_SUCCESS";
export const ARCHIVE_BUSINESS_CENTER_FAIL = "ARCHIVE_BUSINESS_CENTER_FAIL";

// Разархивирование
export const UNARCHIVE_BUSINESS_CENTER_REQUEST =
  "UNARCHIVE_BUSINESS_CENTER_REQUEST";
export const UNARCHIVE_BUSINESS_CENTER_SUCCESS =
  "UNARCHIVE_BUSINESS_CENTER_SUCCESS";
export const UNARCHIVE_BUSINESS_CENTER_FAIL = "UNARCHIVE_BUSINESS_CENTER_FAIL";
